export default [
  "a cappella",
  "abstract hip hop",
  "acid rock",
  "acoustic blues",
  "acoustic chill",
  "acoustic pop",
  "acoustic punk",
  "acoustic",
  "adoracao",
  "adult standards",
  "african rock",
  "afro dancehall",
  "afro house",
  "afrobeat",
  "afrofuturism",
  "afrofuturismo brasileiro",
  "afropop",
  "afroswing",
  "alabama indie",
  "alabama rap",
  "albanian hip hop",
  "albanian pop",
  "alberta country",
  "album rock",
  "albuquerque indie",
  "alt-idol",
  "alt-rock",
  "alternative americana",
  "alternative country",
  "alternative dance",
  "alternative emo",
  "alternative hip hop",
  "alternative metal",
  "alternative pop rock",
  "alternative pop",
  "alternative r&b",
  "alternative rock",
  "alternative",
  "ambeat",
  "ambient folk",
  "ambient pop",
  "ambient worship",
  "ambient",
  "american folk revival",
  "anadolu rock",
  "anime latino",
  "anime rock",
  "anime score",
  "anime",
  "ann arbor indie",
  "anthem emo",
  "anthem worship",
  "anti-folk",
  "antideutsche",
  "antiviral pop",
  "arab pop",
  "arabesk",
  "arabic hip hop",
  "argentine alternative rock",
  "argentine hip hop",
  "argentine indie",
  "argentine punk",
  "argentine reggae",
  "argentine rock",
  "argentine telepop",
  "arkansas country",
  "arkansas hip hop",
  "art pop",
  "art punk",
  "art rock",
  "asian american hip hop",
  "asmr",
  "athens indie",
  "atl hip hop",
  "atl trap",
  "atmosphere",
  "auckland indie",
  "aussie drill",
  "aussietronica",
  "austindie",
  "australian alternative pop",
  "australian alternative rock",
  "australian children's music",
  "australian country",
  "australian dance",
  "australian electropop",
  "australian garage punk",
  "australian hip hop",
  "australian house",
  "australian indie folk",
  "australian indie",
  "australian indigenous",
  "australian metalcore",
  "australian pop",
  "australian psych",
  "australian r&b",
  "australian reggae fusion",
  "australian rock",
  "australian singer-songwriter",
  "australian talent show",
  "australian trap",
  "australian underground hip hop",
  "austrian pop",
  "austropop",
  "avant-garde jazz",
  "axe",
  "azonto",
  "azontobeats",
  "bachata",
  "background music",
  "background piano",
  "bakersfield sound",
  "baltimore indie",
  "banda caliente",
  "banda carnavalera",
  "banda",
  "bandinhas",
  "banjo",
  "barbadian pop",
  "barnmusik",
  "barnsagor",
  "baroque pop",
  "baroque",
  "bass house",
  "bass music",
  "bass trap",
  "basshall",
  "bassline",
  "baton rouge rap",
  "battle rap",
  "bay area indie",
  "bboy",
  "bc underground hip hop",
  "beach house",
  "beatlesque",
  "bebop",
  "bedroom pop",
  "bedroom soul",
  "belarusian hip hop",
  "belgian dance",
  "belgian edm",
  "belgian hip hop",
  "belgian indie",
  "belgian pop",
  "belgian rock",
  "belly dance",
  "belo horizonte indie",
  "bergen indie",
  "bhangra",
  "big band",
  "big beat",
  "big room",
  "binaural",
  "birmingham grime",
  "birmingham hip hop",
  "birmingham metal",
  "bitpop",
  "black metal",
  "black-metal",
  "bluegrass",
  "blues rock",
  "blues",
  "bmore",
  "bolero",
  "boogaloo",
  "boom bap brasileiro",
  "boom bap",
  "bossa nova cover",
  "bossa nova",
  "bossanova",
  "boston hip hop",
  "boston indie",
  "boston metal",
  "boston punk",
  "boston rock",
  "bouncy house",
  "bow pop",
  "boy band",
  "brain waves",
  "brazil",
  "brazilian bass",
  "brazilian ccm",
  "brazilian edm",
  "brazilian gospel",
  "brazilian hip hop",
  "brazilian indie",
  "brazilian jazz",
  "brazilian psychedelic",
  "brazilian punk",
  "brazilian reggae",
  "brazilian rock",
  "breakbeat",
  "brega funk",
  "brega romantico",
  "brighton indie",
  "brill building pop",
  "brisbane indie",
  "british alternative rock",
  "british blues",
  "british folk",
  "british indie rock",
  "british invasion",
  "british singer-songwriter",
  "british soul",
  "british soundtrack",
  "british",
  "britpop",
  "broadway",
  "bronx hip hop",
  "brooklyn drill",
  "brooklyn indie",
  "brostep",
  "brutal death metal",
  "bubble trance",
  "bubblegum dance",
  "bubblegum pop",
  "bulgarian pop",
  "c-pop",
  "cali rap",
  "calming instrumental",
  "canadian americana",
  "canadian ccm",
  "canadian contemporary country",
  "canadian contemporary r&b",
  "canadian country",
  "canadian electronic",
  "canadian electropop",
  "canadian folk",
  "canadian hip hop",
  "canadian indie",
  "canadian latin",
  "canadian metal",
  "canadian pop punk",
  "canadian pop",
  "canadian punk",
  "canadian rock",
  "canadian singer-songwriter",
  "canadian soundtrack",
  "cancion melodica",
  "candy pop",
  "cantautor",
  "canterbury scene",
  "cantopop",
  "canzone d'autore",
  "canzone napoletana",
  "carnaval cadiz",
  "carnaval",
  "cartoon",
  "ccm",
  "cello",
  "celtic metal",
  "celtic punk",
  "celtic rock",
  "celtic",
  "chamame",
  "chamber pop",
  "chamber psych",
  "champeta",
  "channel pop",
  "chanson",
  "chicago blues",
  "chicago drill",
  "chicago hardcore",
  "chicago house",
  "chicago indie",
  "chicago punk",
  "chicago rap",
  "chicago soul",
  "chicago-house",
  "chicano rap",
  "chicha",
  "chihuahua indie",
  "children",
  "children's folk",
  "children's music",
  "chilean indie",
  "chilean rock",
  "chilena",
  "chill beats",
  "chill guitar",
  "chill lounge",
  "chill r&b",
  "chill",
  "chillhop",
  "chillstep",
  "chillwave",
  "chinese electropop",
  "chinese idol pop",
  "chinese indie",
  "chiptune",
  "christian alternative rock",
  "christian hip hop",
  "christian indie",
  "christian metal",
  "christian metalcore",
  "christian music",
  "christian pop",
  "christian relaxative",
  "christian rock",
  "christian trap",
  "christian uplift",
  "christlicher rap",
  "chunchaca",
  "chutney",
  "circuit",
  "classic arab pop",
  "classic belgian pop",
  "classic bollywood",
  "classic canadian rock",
  "classic cantopop",
  "classic colombian pop",
  "classic country pop",
  "classic danish pop",
  "classic dubstep",
  "classic finnish pop",
  "classic finnish rock",
  "classic garage rock",
  "classic girl group",
  "classic hardstyle",
  "classic indo pop",
  "classic iskelma",
  "classic israeli pop",
  "classic italian pop",
  "classic malaysian pop",
  "classic mandopop",
  "classic norwegian pop",
  "classic opm",
  "classic pakistani pop",
  "classic polish pop",
  "classic rock",
  "classic russian pop",
  "classic russian rock",
  "classic schlager",
  "classic soul",
  "classic soundtrack",
  "classic swedish pop",
  "classic thai pop",
  "classic turkish pop",
  "classic uk pop",
  "classical era",
  "classical tenor",
  "classical",
  "classify",
  "club",
  "cologne indie",
  "colombian hip hop",
  "colombian pop",
  "colombian rock",
  "comedy rap",
  "comedy",
  "comic metal",
  "comic",
  "complextro",
  "compositional ambient",
  "conscious hip hop",
  "contemporary country",
  "contemporary gospel",
  "contemporary jazz",
  "contemporary post-bop",
  "contemporary vocal jazz",
  "cool jazz",
  "corrido",
  "corridos tumbados",
  "cosmic american",
  "country blues",
  "country dawn",
  "country gospel",
  "country pop",
  "country rap",
  "country road",
  "country rock",
  "country",
  "coverchill",
  "cowboy western",
  "crunk",
  "cuarteto",
  "cubaton",
  "cumbia chilena",
  "cumbia paraguaya",
  "cumbia peruana",
  "cumbia pop",
  "cumbia ranchera",
  "cumbia santafesina",
  "cumbia sonidera",
  "cumbia villera",
  "cumbia",
  "cyberpunk",
  "czech folk",
  "czech hip hop",
  "czech pop",
  "czech rock",
  "czsk hip hop",
  "dakke dak",
  "dance pop",
  "dance rock",
  "dance",
  "dance-punk",
  "dancehall",
  "dangdut koplo",
  "dangdut remix",
  "dangdut",
  "danish electronic",
  "danish hip hop",
  "danish metal",
  "danish pop rock",
  "danish pop",
  "danish rock",
  "dansband",
  "danseband",
  "dansktop",
  "danspunk",
  "dark post-punk",
  "dark techno",
  "dark trap",
  "dark wave",
  "darksynth",
  "death metal",
  "death-metal",
  "deathcore",
  "deep big room",
  "deep ccm",
  "deep disco house",
  "deep euro house",
  "deep german hip hop",
  "deep groove house",
  "deep house",
  "deep indian pop",
  "deep latin christian",
  "deep new americana",
  "deep pop edm",
  "deep pop r&b",
  "deep regional mexican",
  "deep southern trap",
  "deep talent show",
  "deep tech house",
  "deep tropical house",
  "deep turkish pop",
  "deep underground hip hop",
  "deep-house",
  "dembow",
  "desi hip hop",
  "desi pop",
  "destroy techno",
  "detroit hip hop",
  "detroit trap",
  "detroit-techno",
  "dfw rap",
  "dinner jazz",
  "dirty south rap",
  "disco house",
  "disco polo",
  "disco",
  "discofox",
  "disney",
  "diva house",
  "dixieland",
  "djent",
  "dmv rap",
  "dominican pop",
  "dong-yo",
  "doo-wop",
  "doom metal",
  "double drumming",
  "downtempo",
  "dream pop",
  "dreamo",
  "drift",
  "drill francais",
  "drill",
  "drone",
  "drum and bass",
  "drum-and-bass",
  "dub",
  "dubstep",
  "duranguense",
  "dutch cabaret",
  "dutch edm",
  "dutch hip hop",
  "dutch house",
  "dutch indie",
  "dutch metal",
  "dutch pop",
  "dutch rock",
  "dutch trance",
  "dutch trap pop",
  "e6fi",
  "early modern classical",
  "early music",
  "early romantic era",
  "early us punk",
  "east coast hip hop",
  "east coast reggae",
  "easy listening",
  "easycore",
  "eau claire indie",
  "ebm",
  "ecm-style jazz",
  "ectofolk",
  "ecuadorian pop",
  "edm",
  "edmonton indie",
  "egyptian pop",
  "el paso indie",
  "electra",
  "electric blues",
  "electro house",
  "electro jazz",
  "electro latino",
  "electro swing",
  "electro",
  "electro-industrial",
  "electroclash",
  "electronic rock",
  "electronic trap",
  "electronic",
  "electronica argentina",
  "electronica",
  "electropop",
  "electropowerpop",
  "emo mexicano",
  "emo rap italiano",
  "emo rap",
  "emo",
  "english indie rock",
  "environmental",
  "epicore",
  "escape room",
  "ethereal wave",
  "etherpop",
  "ethnotronica",
  "euphoric hardstyle",
  "eurodance",
  "europop",
  "eurovision",
  "experimental hip hop",
  "experimental pop",
  "experimental rock",
  "experimental",
  "fado",
  "filmi",
  "filter house",
  "filthstep",
  "fingerstyle",
  "finnish dance pop",
  "finnish hip hop",
  "finnish metal",
  "finnish pop",
  "finnish power metal",
  "finnish trap",
  "flamenco fusion",
  "flamenco guitar",
  "flamenco urbano",
  "flamenco",
  "float house",
  "florida rap",
  "focus beats",
  "focus",
  "folclore salteno",
  "folk brasileiro",
  "folk metal",
  "folk punk",
  "folk rock italiano",
  "folk rock",
  "folk",
  "folk-pop",
  "folklore argentino",
  "folktronica",
  "forro de favela",
  "forro",
  "fourth world",
  "francoton",
  "freak folk",
  "free jazz",
  "freestyle",
  "french hip hop",
  "french indie pop",
  "french indietronica",
  "french jazz",
  "french metal",
  "french pop",
  "french reggae",
  "french rock",
  "french shoegaze",
  "french soundtrack",
  "french",
  "frenchcore",
  "funk 150 bpm",
  "funk bh",
  "funk carioca",
  "funk consciente",
  "funk das antigas",
  "funk metal",
  "funk ostentacao",
  "funk paulista",
  "funk rock",
  "funk",
  "funky tech house",
  "future bass",
  "future funk",
  "future garage",
  "future house",
  "future rock",
  "g funk",
  "gabba",
  "gaming dubstep",
  "gaming edm",
  "gangster rap",
  "garage psych",
  "garage rock revival",
  "garage rock",
  "garage",
  "gauze pop",
  "gbvfi",
  "german alternative rap",
  "german alternative rock",
  "german baroque",
  "german cloud rap",
  "german dance",
  "german hard rock",
  "german hip hop",
  "german house",
  "german indie folk",
  "german indie",
  "german metal",
  "german metalcore",
  "german oi",
  "german pop rock",
  "german pop",
  "german punk",
  "german reggae",
  "german rock",
  "german singer-songwriter",
  "german soundtrack",
  "german techno",
  "german trap",
  "german underground rap",
  "german",
  "ghanaian hip hop",
  "ghazal",
  "girl group",
  "glam metal",
  "glam rock",
  "glee club",
  "glitch hop",
  "glitch",
  "glitchcore",
  "gospel antigas",
  "gospel r&b",
  "gospel",
  "goth",
  "gothenburg indie",
  "gothenburg metal",
  "gothic metal",
  "gothic rock",
  "gothic symphonic metal",
  "grave wave",
  "greek hip hop",
  "greek pop",
  "greek trap",
  "grime",
  "grindcore",
  "groove gospel",
  "groove metal",
  "groove room",
  "groove",
  "grunge",
  "grupera",
  "gruperas inmortales",
  "guadalajara indie",
  "guaracha",
  "guitar",
  "gymcore",
  "hamburg electronic",
  "hamburg hip hop",
  "hands up",
  "happy hardcore",
  "happy",
  "hard alternative",
  "hard bass",
  "hard bop",
  "hard rock brasileiro",
  "hard rock",
  "hard-rock",
  "hardcore hip hop",
  "hardcore punk",
  "hardcore techno",
  "hardcore",
  "hardstyle",
  "harlem hip hop",
  "harlem renaissance",
  "haryanvi pop",
  "hawaiian hip hop",
  "hawaiian",
  "healing",
  "heartland rock",
  "heavy-metal",
  "hi-nrg",
  "hindi hip hop",
  "hindi indie",
  "hip hop quebecois",
  "hip hop tuga",
  "hip hop",
  "hip house",
  "hip pop",
  "hip-hop",
  "hoerspiel",
  "holidays",
  "hollywood",
  "honky-tonk",
  "hopebeat",
  "horror punk",
  "house",
  "houston rap",
  "hungarian pop",
  "hungarian rock",
  "hurdy-gurdy",
  "hyperpop",
  "hyphy",
  "icelandic classical",
  "icelandic indie",
  "icelandic pop",
  "icelandic rock",
  "idm",
  "idol rock",
  "idol",
  "impressionism",
  "indian edm",
  "indian indie",
  "indian instrumental",
  "indian singer-songwriter",
  "indian",
  "indiana hip hop",
  "indie anthem-folk",
  "indie cafe pop",
  "indie catala",
  "indie deutschrap",
  "indie electropop",
  "indie folk",
  "indie game soundtrack",
  "indie garage rock",
  "indie jazz",
  "indie liguria",
  "indie pop rap",
  "indie pop",
  "indie poptimism",
  "indie punk",
  "indie quebecois",
  "indie r&b",
  "indie rock mexicano",
  "indie rock",
  "indie rockism",
  "indie soul",
  "indie surf",
  "indie triste",
  "indie viet",
  "indie",
  "indie-pop",
  "indiecoustica",
  "indietronica",
  "indonesian alternative rock",
  "indonesian folk",
  "indonesian hip hop",
  "indonesian indie",
  "indonesian jazz",
  "indonesian pop punk",
  "indonesian pop",
  "indonesian r&b",
  "indonesian rock",
  "indonesian worship",
  "industrial hip hop",
  "industrial metal",
  "industrial rock",
  "industrial",
  "instrumental funk",
  "instrumental grime",
  "instrumental rock",
  "intelligent dance music",
  "iranian",
  "irish country",
  "irish folk",
  "irish hip hop",
  "irish pop",
  "irish rock",
  "irish singer-songwriter",
  "iskelma",
  "israeli mediterranean",
  "israeli pop",
  "israeli rock",
  "italian alternative",
  "italian arena pop",
  "italian baroque",
  "italian disco",
  "italian hip hop",
  "italian indie pop",
  "italian opera",
  "italian pop rock",
  "italian pop",
  "italian reggae",
  "italian soundtrack",
  "italian tenor",
  "italian underground hip hop",
  "italo dance",
  "j-acoustic",
  "j-dance",
  "j-division",
  "j-idol",
  "j-metal",
  "j-pixie",
  "j-pop boy group",
  "j-pop girl group",
  "j-pop",
  "j-poprock",
  "j-rap",
  "j-rock",
  "jam band",
  "jamgrass",
  "jangle pop",
  "japanese alternative rock",
  "japanese chillhop",
  "japanese city pop",
  "japanese classical",
  "japanese electropop",
  "japanese emo",
  "japanese instrumental",
  "japanese pop punk",
  "japanese post-hardcore",
  "japanese punk rock",
  "japanese r&b",
  "japanese singer-songwriter",
  "japanese soul",
  "japanese soundtrack",
  "japanese vgm",
  "jawaiian",
  "jazz blues",
  "jazz boom bap",
  "jazz funk",
  "jazz fusion",
  "jazz guitar",
  "jazz piano",
  "jazz rap",
  "jazz saxophone",
  "jazz trio",
  "jazz trumpet",
  "jazz",
  "jazztronica",
  "jewish pop",
  "jovem guarda",
  "jump up",
  "jungle",
  "k-indie",
  "k-pop boy group",
  "k-pop girl group",
  "k-pop",
  "k-rap",
  "kabarett",
  "kansas city hip hop",
  "karadeniz halk muzigi",
  "kawaii future bass",
  "kazakh pop",
  "kentucky hip hop",
  "kentucky indie",
  "khaliji",
  "kids",
  "kindermusik",
  "kirtan",
  "kiwi rock",
  "kizomba",
  "kleine hoerspiel",
  "korean ost",
  "korean pop",
  "korean r&b",
  "kosovan pop",
  "kurdish pop",
  "kwaito house",
  "la indie",
  "la pop",
  "laboratorio",
  "laiko",
  "late romantic era",
  "latin afrobeat",
  "latin alternative",
  "latin arena pop",
  "latin christian",
  "latin classical",
  "latin funk",
  "latin hip hop",
  "latin jazz",
  "latin metal",
  "latin pop",
  "latin rock",
  "latin soundtrack",
  "latin talent show",
  "latin viral pop",
  "latin worship",
  "latin",
  "latino",
  "latintronica",
  "lds youth",
  "lebanese pop",
  "leicester indie",
  "lesen",
  "levenslied",
  "lgbtq+ hip hop",
  "liedermacher",
  "lilith",
  "liquid funk",
  "lithuanian electronic",
  "liverpool indie",
  "livetronica",
  "lo-fi beats",
  "lo-fi chill",
  "lo-fi house",
  "lo-fi",
  "london rap",
  "louisiana blues",
  "lounge",
  "louvor",
  "lovers rock",
  "lullaby",
  "madchester",
  "magyar alternative",
  "mainland chinese pop",
  "malay",
  "malaysian indie",
  "malaysian mandopop",
  "malaysian pop",
  "mambo",
  "manchester hip hop",
  "mande pop",
  "mandopop",
  "manguebeat",
  "manila sound",
  "mariachi cristiano",
  "mariachi",
  "medieval folk",
  "medieval rock",
  "meditation",
  "melancholia",
  "melbourne bounce international",
  "melbourne bounce",
  "mellow gold",
  "melodic death metal",
  "melodic dubstep",
  "melodic hardcore",
  "melodic metal",
  "melodic metalcore",
  "melodic rap",
  "melodic techno",
  "melodic thrash",
  "meme rap",
  "memphis hip hop",
  "memphis soul",
  "merengue",
  "merseybeat",
  "metal",
  "metal-misc",
  "metalcore",
  "metallic hardcore",
  "metropopolis",
  "mexican classic rock",
  "mexican hip hop",
  "mexican indie",
  "mexican pop punk",
  "mexican pop",
  "mexican rock",
  "mexican rock-and-roll",
  "miami hip hop",
  "microhouse",
  "middle earth",
  "midwest emo",
  "milan indie",
  "minecraft",
  "minimal tech house",
  "minimal techno",
  "minimal-techno",
  "minimalism",
  "minneapolis indie",
  "minneapolis sound",
  "minnesota hip hop",
  "mississippi hip hop",
  "mizrahi",
  "modern alternative rock",
  "modern blues rock",
  "modern blues",
  "modern bollywood",
  "modern country rock",
  "modern dream pop",
  "modern folk rock",
  "modern funk",
  "modern hard rock",
  "modern power pop",
  "modern reggae",
  "modern rock",
  "modern salsa",
  "modern ska punk",
  "modern southern rock",
  "moombahton",
  "morelos indie",
  "moroccan pop",
  "motown",
  "movie tunes",
  "movies",
  "mpb",
  "music box",
  "musica andina",
  "musica aragonesa",
  "musica catalana",
  "musica costena",
  "musica de fondo",
  "musica gaucha tradicionalista",
  "musica infantil",
  "musica para ninos",
  "musica tradicional cubana",
  "musica triste brasileira",
  "musique pour enfants",
  "muziek voor kinderen",
  "naija worship",
  "narodna muzika",
  "nashville hip hop",
  "nashville indie",
  "nashville singer-songwriter",
  "nashville sound",
  "native american",
  "nederlandse hardstyle",
  "nederpop",
  "neo classical metal",
  "neo mellow",
  "neo r&b",
  "neo soul",
  "neo-classical",
  "neo-progressive",
  "neo-psychedelic",
  "neo-singer-songwriter",
  "neo-synthpop",
  "neoclassical darkwave",
  "neomelodici",
  "neon pop punk",
  "nerdcore brasileiro",
  "neue deutsche harte",
  "neue deutsche welle",
  "new age piano",
  "new age",
  "new americana",
  "new comedy",
  "new french touch",
  "new jack swing",
  "new jersey hardcore",
  "new jersey indie",
  "new jersey punk",
  "new jersey rap",
  "new orleans jazz",
  "new orleans rap",
  "new rave",
  "new romantic",
  "new wave pop",
  "new wave",
  "new weird america",
  "new york drill",
  "new-age",
  "new-release",
  "nigerian hip hop",
  "nigerian pop",
  "nightcore",
  "nightrun",
  "ninja",
  "nintendocore",
  "noise pop",
  "noise rock",
  "nordic house",
  "nordic soundtrack",
  "norteno",
  "norteno-sax",
  "north carolina hip hop",
  "north carolina indie",
  "northern irish indie",
  "northern soul",
  "norwegian country",
  "norwegian hip hop",
  "norwegian indie",
  "norwegian pop rap",
  "norwegian pop",
  "norwegian rock",
  "nottingham indie",
  "nouvelle chanson francaise",
  "nova mpb",
  "nova musica pernambucana",
  "nu disco",
  "nu gaze",
  "nu jazz",
  "nu metal",
  "nu-cumbia",
  "nu-metalcore",
  "nueva cancion",
  "nuevo regional mexicano",
  "nursery",
  "nwobhm",
  "nyc pop",
  "nyc rap",
  "nz pop",
  "nz reggae",
  "oakland hip hop",
  "oakland indie",
  "oc rap",
  "ohio hip hop",
  "okinawan pop",
  "oklahoma country",
  "old school dancehall",
  "old school hip hop",
  "old school rap francais",
  "old school thrash",
  "old-time",
  "opera metal",
  "opera",
  "operatic pop",
  "opm",
  "organic electronic",
  "organic house",
  "orgcore",
  "orlando indie",
  "otacore",
  "ottawa rap",
  "outlaw country",
  "outsider house",
  "oxford indie",
  "oyun havasi",
  "pagode baiano",
  "pagode novo",
  "pagode",
  "pakistani hip hop",
  "palm desert scene",
  "panamanian pop",
  "papuri",
  "parody",
  "partido alto",
  "party",
  "partyschlager",
  "permanent wave",
  "perreo",
  "persian pop",
  "peruvian hip hop",
  "peruvian rock",
  "pet calming",
  "philippines-opm",
  "philly indie",
  "philly rap",
  "philly soul",
  "phonk",
  "pianissimo",
  "piano blues",
  "piano cover",
  "piano rock",
  "piano",
  "pinoy alternative rap",
  "pinoy hip hop",
  "pinoy indie",
  "pinoy pop punk",
  "pinoy r&b",
  "pinoy reggae",
  "pinoy rock",
  "pinoy trap",
  "piseiro",
  "pittsburgh indie",
  "pittsburgh rap",
  "pixie",
  "polish alternative rap",
  "polish alternative",
  "polish classical",
  "polish hip hop",
  "polish indie",
  "polish pop",
  "polish rock",
  "polish trap",
  "political hip hop",
  "polynesian pop",
  "pony",
  "pop argentino",
  "pop chileno",
  "pop edm",
  "pop electronico",
  "pop emo",
  "pop flamenco",
  "pop folk",
  "pop house",
  "pop lgbtq+ brasileira",
  "pop nacional",
  "pop peruano",
  "pop punk",
  "pop quebecois",
  "pop rap brasileiro",
  "pop rap",
  "pop reggaeton",
  "pop rock brasileiro",
  "pop rock",
  "pop romantico",
  "pop teen brasileiro",
  "pop urbaine",
  "pop venezolano",
  "pop violin",
  "pop virale italiano",
  "pop",
  "pop-film",
  "popping",
  "popwave",
  "portland hip hop",
  "portland indie",
  "portuguese pop",
  "post-disco",
  "post-dubstep",
  "post-grunge",
  "post-hardcore",
  "post-metal",
  "post-minimalism",
  "post-punk argentina",
  "post-punk",
  "post-rock",
  "post-romantic era",
  "post-screamo",
  "post-teen pop",
  "power metal",
  "power pop",
  "power-pop",
  "preschool children's music",
  "progressive bluegrass",
  "progressive deathcore",
  "progressive electro house",
  "progressive groove metal",
  "progressive house",
  "progressive jazz fusion",
  "progressive metal",
  "progressive metalcore",
  "progressive post-hardcore",
  "progressive psytrance",
  "progressive rock",
  "progressive trance",
  "progressive uplifting trance",
  "progressive-house",
  "protopunk",
  "psych-rock",
  "psychedelic doom",
  "psychedelic hip hop",
  "psychedelic pop",
  "psychedelic rock",
  "psychedelic trance",
  "pub rock",
  "puerto rican pop",
  "puerto rican rock",
  "punjabi hip hop",
  "punjabi pop",
  "punk 'n' roll",
  "punk blues",
  "punk urbano",
  "punk",
  "punk-rock",
  "quebec indie",
  "queens hip hop",
  "quiet storm",
  "r&b argentino",
  "r&b brasileiro",
  "r&b en espanol",
  "r&b italiano",
  "r&b",
  "r-n-b",
  "rai",
  "rainy-day",
  "ranchera",
  "rap algerien",
  "rap baiano",
  "rap calme",
  "rap catala",
  "rap chileno",
  "rap conciencia",
  "rap conscient",
  "rap cristiano",
  "rap df",
  "rap dominicano",
  "rap espanol",
  "rap francais",
  "rap inde",
  "rap ivoire",
  "rap latina",
  "rap maroc",
  "rap marseille",
  "rap metal",
  "rap mineiro",
  "rap montrealais",
  "rap napoletano",
  "rap rock",
  "rap tunisien",
  "rap underground espanol",
  "rap underground mexicano",
  "rap",
  "rave funk",
  "rave",
  "rawstyle",
  "reading",
  "rebel blues",
  "red dirt",
  "redneck",
  "reggae en espanol",
  "reggae fusion",
  "reggae rock",
  "reggae tuga",
  "reggae",
  "reggaeton chileno",
  "reggaeton colombiano",
  "reggaeton cristiano",
  "reggaeton flow",
  "reggaeton mexicano",
  "reggaeton",
  "regional mexican",
  "relaxative",
  "retro soul",
  "rhode island rap",
  "rhythm and blues",
  "riddim",
  "rif",
  "ritmo kombina",
  "road-trip",
  "rock alternativo brasileiro",
  "rock andaluz",
  "rock baiano",
  "rock brasiliense",
  "rock catala",
  "rock cristiano",
  "rock drums",
  "rock en espanol",
  "rock gaucho",
  "rock gospel brasileiro",
  "rock kapak",
  "rock mineiro",
  "rock nacional brasileiro",
  "rock nacional",
  "rock steady",
  "rock urbano mexicano",
  "rock uruguayo",
  "rock",
  "rock-and-roll",
  "rock-n-roll",
  "rockabilly",
  "romance",
  "romanian hip hop",
  "romanian pop",
  "romanian trap",
  "romantico",
  "rome indie",
  "roots americana",
  "roots reggae",
  "roots rock",
  "roots worship",
  "rumba",
  "rune folk",
  "russelater",
  "russian ccm",
  "russian dance pop",
  "russian dance",
  "russian electronic",
  "russian gangster rap",
  "russian hip hop",
  "russian pop",
  "russian post-punk",
  "russian punk",
  "russian rock",
  "russian romanticism",
  "russian trap",
  "sacramento hip hop",
  "sacramento indie",
  "sad rap",
  "sad",
  "salsa choke",
  "salsa colombiana",
  "salsa international",
  "salsa peruana",
  "salsa puertorriquena",
  "salsa venezolana",
  "salsa",
  "samba de roda",
  "samba moderno",
  "samba reggae",
  "samba",
  "samba-jazz",
  "samba-rock",
  "san diego rap",
  "saskatchewan indie",
  "scam rap",
  "scandinavian r&b",
  "scandipop",
  "schlager",
  "schweizer rap",
  "scorecore",
  "scottish indie rock",
  "scottish indie",
  "scottish new wave",
  "scottish rock",
  "scottish singer-songwriter",
  "scream rap",
  "screamo",
  "seattle hip hop",
  "seattle indie",
  "sertanejo pop",
  "sertanejo tradicional",
  "sertanejo universitario",
  "sertanejo",
  "sevdah",
  "shamanic",
  "sheffield indie",
  "shibuya-kei",
  "shimmer pop",
  "shiver pop",
  "shoegaze",
  "sholawat",
  "show tunes",
  "show-tunes",
  "shred",
  "shush",
  "singaporean mandopop",
  "singaporean pop",
  "singer-songwriter",
  "ska argentino",
  "ska chileno",
  "ska mexicano",
  "ska punk",
  "ska revival",
  "ska",
  "skate punk",
  "sky room",
  "slayer",
  "sleaze rock",
  "sleep",
  "slowcore",
  "sludge metal",
  "small room",
  "smooth jazz",
  "smooth saxophone",
  "soca",
  "socal pop punk",
  "social media pop",
  "soft rock",
  "songwriter",
  "soul blues",
  "soul jazz",
  "soul",
  "sound team",
  "sound",
  "soundtrack",
  "soundtracks",
  "south african alternative",
  "south african pop",
  "south african rock",
  "south carolina hip hop",
  "southern hip hop",
  "southern rock",
  "southern soul",
  "space rock",
  "spanish folk metal",
  "spanish hip hop",
  "spanish indie pop",
  "spanish metal",
  "spanish modern rock",
  "spanish new wave",
  "spanish pop rock",
  "spanish pop",
  "spanish punk",
  "spanish rock",
  "spanish",
  "speed metal",
  "st louis rap",
  "steampunk",
  "stomp and flutter",
  "stomp and holler",
  "stomp pop",
  "stoner metal",
  "stoner rock",
  "stride",
  "strut",
  "study",
  "sufi",
  "summer",
  "sunshine pop",
  "suomi rock",
  "supergroup",
  "surf music",
  "surf punk",
  "swamp rock",
  "swancore",
  "swedish alternative rock",
  "swedish americana",
  "swedish country",
  "swedish dancehall",
  "swedish death metal",
  "swedish electropop",
  "swedish eurodance",
  "swedish gangsta rap",
  "swedish hard rock",
  "swedish hip hop",
  "swedish idol pop",
  "swedish indie folk",
  "swedish indie pop",
  "swedish indie rock",
  "swedish jazz",
  "swedish metal",
  "swedish pop",
  "swedish power metal",
  "swedish reggae",
  "swedish singer-songwriter",
  "swedish soul",
  "swedish synthpop",
  "swedish trap pop",
  "swedish trap",
  "swedish tropical house",
  "swedish",
  "swing",
  "swiss hip hop",
  "swiss indie",
  "swiss pop",
  "symphonic black metal",
  "symphonic metal",
  "symphonic power metal",
  "symphonic rock",
  "synth funk",
  "synth-pop",
  "synthpop",
  "synthwave",
  "tagalog worship",
  "taiwan hip hop",
  "taiwan indie",
  "taiwan pop",
  "taiwan singer-songwriter",
  "talent show",
  "tamil hip hop",
  "tamil pop",
  "tango",
  "tech house",
  "technical death metal",
  "techno",
  "tecnobanda",
  "tecnobrega",
  "teen pop",
  "tejano",
  "tekk",
  "tennessee hip hop",
  "tex-mex",
  "texas blues",
  "texas country",
  "texas latin rap",
  "texas pop punk",
  "thai hip hop",
  "thai idol",
  "thai indie pop",
  "thai indie rock",
  "thai indie",
  "thai pop",
  "thai rock",
  "theme",
  "thrash metal",
  "torch song",
  "toronto indie",
  "toronto rap",
  "traditional blues",
  "traditional folk",
  "trance brasileiro",
  "trance",
  "trancecore",
  "transpop",
  "trap argentino",
  "trap baiano",
  "trap brasileiro",
  "trap carioca",
  "trap chileno",
  "trap espanol",
  "trap funk",
  "trap italiana",
  "trap latino",
  "trap mexicano",
  "trap queen",
  "trap soul",
  "trap venezolano",
  "trap",
  "traprun",
  "tribal house",
  "trip hop",
  "trip-hop",
  "tropical house",
  "tropical",
  "tropicalia",
  "trova",
  "turbo folk",
  "turkish alternative rock",
  "turkish alternative",
  "turkish edm",
  "turkish folk",
  "turkish hip hop",
  "turkish instrumental",
  "turkish jazz",
  "turkish pop",
  "turkish psych",
  "turkish rock",
  "turkish singer-songwriter",
  "turkish trap pop",
  "turkish trap",
  "turkish",
  "turntablism",
  "uk alternative hip hop",
  "uk alternative pop",
  "uk americana",
  "uk contemporary r&b",
  "uk dance",
  "uk dancehall",
  "uk dnb",
  "uk doom metal",
  "uk drill",
  "uk funky",
  "uk garage",
  "uk hip hop",
  "uk house",
  "uk metalcore",
  "uk pop punk",
  "uk pop",
  "uk post-punk",
  "uk reggae",
  "uk worship",
  "ukg revival",
  "ukrainian pop",
  "ukrainian rock",
  "umbanda",
  "underground hip hop",
  "underground rap",
  "uplifting trance",
  "uptempo hardcore",
  "urban contemporary",
  "v-pop",
  "vallenato moderno",
  "vallenato",
  "vancouver indie",
  "vapor pop",
  "vapor soul",
  "vapor trap",
  "vapor twitch",
  "vaporwave",
  "variete francaise",
  "vegas indie",
  "velha guarda",
  "venezuelan hip hop",
  "venezuelan rock",
  "veracruz indie",
  "video game music",
  "viking folk",
  "viking metal",
  "vintage italian soundtrack",
  "violao",
  "viral pop",
  "viral trap",
  "virginia hip hop",
  "virginia metal",
  "visual kei",
  "vocal house",
  "vocal jazz",
  "vocaloid",
  "volksmusik",
  "volkspop",
  "washington indie",
  "water",
  "wave",
  "welsh metal",
  "welsh rock",
  "west coast rap",
  "west coast trap",
  "white noise",
  "women's music",
  "wonky",
  "work-out",
  "world fusion",
  "world meditation",
  "world worship",
  "world",
  "world-music",
  "worship",
  "wrestling",
  "yacht rock",
  "ye ye",
  "yugoslav rock",
  "zhongguo feng",
  "zolo",
  "zouk riddim",
];
